# Generated by Django 5.1.5 on 2025-02-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('e_title', models.CharField(default='', max_length=1000, null=True)),
                ('e_author', models.CharField(default='', max_length=200, null=True)),
                ('e_contributors', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('e_description', models.TextField(blank=True, default='', null=True)),
                ('e_country', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('e_place', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('e_source', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('e_language', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('e_genre', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditVideoWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('e_start', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('e_end', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
