# Generated by Django 5.1.5 on 2025-02-05 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editvideos', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='editvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editvideos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editvideowrapper',
            name='edit_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='editvideos.editvideo'),
        ),
        migrations.AddField(
            model_name='editvideowrapper',
            name='origin_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_video', to='videos.video'),
        ),
    ]
