version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - shared_network

  eva_server:
    build: 
      context: ./eva_annotation_board_backend
      dockerfile: Dockerfile.prod
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    environment:
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - VIRTUAL_HOST=admin.talkingobjectsarchive.org    # Nginx Proxy
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=admin.talkingobjectsarchive.org   # SSL Domain
      - LETSENCRYPT_EMAIL=dain-p@visual-intelligence.org # SSL Email
    depends_on:
      - db
    networks: 
      - shared_network
  eva_annotation_board_client:
    build: 
      context: ./eva_annotation_board_client
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3000"
    env_file:
      - ./eva_annotation_board_client/.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - VIRTUAL_HOST=board.talkingobjectsarchive.org    # Nginx Proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=board.talkingobjectsarchive.org   # SSL Domain
      - LETSENCRYPT_EMAIL=dain-p@visual-intelligence.org # SSL Email
    depends_on:
      - eva_server
    networks:
      - shared_network
        

volumes:
  postgres_data:

networks:
  shared_network:
    external: true
