# Generated by Django 5.1.5 on 2025-02-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pandora_id', models.CharField(blank=True, max_length=10, null=True)),
                ('video_id', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('end', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('value', models.JSONField()),
                ('type', models.CharField(default='categoryLayer', editable=False, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pandora_id', models.CharField(blank=True, max_length=10, null=True)),
                ('video_id', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('end', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('value', models.JSONField()),
                ('type', models.CharField(default='dataLayer', editable=False, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pandora_id', models.CharField(blank=True, max_length=10, null=True)),
                ('video_id', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('end', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('value', models.JSONField()),
                ('type', models.CharField(default='eventLayer', editable=False, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Narration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pandora_id', models.CharField(blank=True, max_length=10, null=True)),
                ('video_id', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('end', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('value', models.JSONField()),
                ('type', models.CharField(default='narrationLayer', editable=False, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pandora_id', models.CharField(blank=True, max_length=10, null=True)),
                ('video_id', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('end', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('value', models.JSONField()),
                ('type', models.CharField(default='placeLayer', editable=False, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pandora_id', models.CharField(blank=True, max_length=10, null=True)),
                ('video_id', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('end', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('value', models.JSONField()),
                ('type', models.CharField(default='referenceLayer', editable=False, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pandora_id', models.CharField(blank=True, max_length=10, null=True)),
                ('video_id', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('end', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('value', models.JSONField()),
                ('type', models.CharField(default='tagLayer', editable=False, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
