# Generated by Django 5.1.5 on 2025-02-05 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotations', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationwrapper',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='videos.video'),
        ),
        migrations.AddField(
            model_name='category',
            name='annotation_wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_annotations', to='annotations.annotationwrapper'),
        ),
        migrations.AddField(
            model_name='data',
            name='annotation_wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_annotations', to='annotations.annotationwrapper'),
        ),
        migrations.AddField(
            model_name='event',
            name='annotation_wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_annotations', to='annotations.annotationwrapper'),
        ),
        migrations.AddField(
            model_name='narration',
            name='annotation_wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narration_annotations', to='annotations.annotationwrapper'),
        ),
        migrations.AddField(
            model_name='place',
            name='annotation_wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_annotations', to='annotations.annotationwrapper'),
        ),
        migrations.AddField(
            model_name='reference',
            name='annotation_wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_annotations', to='annotations.annotationwrapper'),
        ),
        migrations.AddField(
            model_name='tag',
            name='annotation_wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_annotations', to='annotations.annotationwrapper'),
        ),
    ]
