# Generated by Django 5.1.5 on 2025-02-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='type',
            field=models.CharField(blank=True, default='raw', max_length=1000, null=True),
        ),
    ]
