# Generated by Django 5.1.5 on 2025-02-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_clip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='type',
            field=models.CharField(blank=True, default='clip', max_length=1000, null=True),
        ),
    ]
