# Generated by Django 5.1.5 on 2025-02-05 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=1000, null=True)),
                ('pandora_id', models.CharField(max_length=10)),
                ('author', models.CharField(default='', max_length=200, null=True)),
                ('contributors', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('country', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('place', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('genre', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('start', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('end', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('poster', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
