# Generated by Django 5.1.5 on 2025-02-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
