# Generated by Django 5.1.5 on 2025-02-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
